kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-setup-route-reader-binding-{{ .Values.app.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
subjects:
- kind: ServiceAccount
  name: demo-setup
  namespace: {{ .Values.app.namespace }}
roleRef:
  kind: ClusterRole
  name: route-reader-{{ .Values.app.name }}
  apiGroup: rbac.authorization.k8s.io