kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elyra-pipelines-{{ .Values.app.workbench.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.workbench.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ds-pipeline-user-access-pipelines-definition