apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-connection-{{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: commonPassword
      remoteRef:
        key: secrets/janusidp/common_password
        property: password
  target:
    name: aws-connection-{{ .Values.app.name }}
    template:
      type: Opaque
      metadata:
        labels:
          opendatahub.io/dashboard: 'true'
          opendatahub.io/managed: 'true'
        annotations:
          opendatahub.io/connection-type: s3
          openshift.io/display-name: {{ .Values.app.name }}-models
      data:
        AWS_ACCESS_KEY_ID: minio
        AWS_DEFAULT_REGION: us-east-1
        AWS_S3_BUCKET: models
        AWS_S3_ENDPOINT: http://minio.ic-shared-minio.svc.cluster.local:9000
        AWS_SECRET_ACCESS_KEY: '{{ "{{" }} .commonPassword {{ "}}" }}'

