kind: Service
apiVersion: v1
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432

