kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
