kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-reader-{{ .Values.app.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-4'
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]