app:
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}-ai
  cluster: ${{values.cluster}}
  user: ${{values.user}}
  model:
    name: ${{values.model_name}}
    maxLength: ${{values.model_max_length}}
  workbench:
    name: 'my-workbench'
    image: pytorch:2024.1
  dashboard:
    route: https://rhods-dashboard-redhat-ods-applications${{values.cluster}}
  documentation:
    version: "${{values.rhoai_doc_version}}"

git:
  branch: master
  repo: ${{values.source_repository}}
  host: ${{ values.repository_host }}
